name: test
on: [push]

env:
  GO_VERSION: 1.18.x

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup golang ${{ env.GO_VERSION }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: make setup
      - name: Lint
        run: make lint
      - name: Test
        run: make test
